name: ijude_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Design ---
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  
  # --- Fontes (Versão estável) ---
  google_fonts: ^6.1.0

  # --- Conexão ---
  http: ^1.2.0

  # --- Inputs ---
  mask_text_input_formatter: ^2.9.0
  pinput: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true